/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIPrincipal.java
 *
 * Created on 03/08/2010, 00:21:44
 */

package ic.faculdadedombosco.visao.gui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Anderson
 */
public class GUIPrincipal extends javax.swing.JFrame {

    //Persistencia pers = new Persistencia();

    /** Creates new form GUIPrincipal */
    public GUIPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //pers.AbrirConexao();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemImprimir = new javax.swing.JMenuItem();
        itemSeparador = new javax.swing.JPopupMenu.Separator();
        itemDeMenuSair = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        itemDeMenuAgendamento = new javax.swing.JMenuItem();
        itemDeMenuEquipamento = new javax.swing.JMenuItem();
        itemDeMenuGradeDisciplina = new javax.swing.JMenuItem();
        itemDeMenuRecurso = new javax.swing.JMenuItem();
        itemDeMenuUsuario = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        itemDeMenuRelatorioDeAgendamento = new javax.swing.JMenuItem();
        itemDeMenuRelatorioDeEquipamento = new javax.swing.JMenuItem();
        itemDeMenuRelatorioDeGradeDisciplina = new javax.swing.JMenuItem();
        itemDeMenuRelatorioDeRecurso = new javax.swing.JMenuItem();
        itemDeMenuRelatorioDeUsuario = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        itemDeMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IC - Faculdade Dom Bosco de Porto Alegre");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/faculdadedombosco/imagens/face_bosco.jpg"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel2.setBounds(0, 0, 1240, 760);
        desktopPane.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jToolBar1.setFloatable(false);
        jToolBar1.setEnabled(false);

        jLabel1.setText("Patrocinado pela Faculdade Dom Bosco - Rua Marechal José Inácio da Silva, nº 355 Bairro Passo d'Areia Porto Alegre, RS - Telefones/Fax: (0xx51) 3361.6700 (0xx51) 3345.3668 - E-mail: faculdade@dombosco.net");
        jToolBar1.add(jLabel1);

        menuArquivo.setText("Arquivo");

        itemImprimir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        itemImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/faculdadedombosco/imagens/imprimir.png"))); // NOI18N
        itemImprimir.setText("Imprimir");
        itemImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemImprimirActionPerformed(evt);
            }
        });
        menuArquivo.add(itemImprimir);
        menuArquivo.add(itemSeparador);

        itemDeMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        itemDeMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/faculdadedombosco/imagens/sair.png"))); // NOI18N
        itemDeMenuSair.setText("Sair");
        itemDeMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(itemDeMenuSair);

        menuBar.add(menuArquivo);

        menuCadastro.setText("Cadastro");

        itemDeMenuAgendamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        itemDeMenuAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/faculdadedombosco/imagens/agendamento.png"))); // NOI18N
        itemDeMenuAgendamento.setText("Agendamento");
        itemDeMenuAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuAgendamentoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemDeMenuAgendamento);

        itemDeMenuEquipamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        itemDeMenuEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/faculdadedombosco/imagens/equipamento.png"))); // NOI18N
        itemDeMenuEquipamento.setText("Equipamento");
        itemDeMenuEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuEquipamentoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemDeMenuEquipamento);

        itemDeMenuGradeDisciplina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        itemDeMenuGradeDisciplina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/faculdadedombosco/imagens/grade_disciplina.png"))); // NOI18N
        itemDeMenuGradeDisciplina.setText("Grade Disciplina");
        itemDeMenuGradeDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuGradeDisciplinaActionPerformed(evt);
            }
        });
        menuCadastro.add(itemDeMenuGradeDisciplina);

        itemDeMenuRecurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        itemDeMenuRecurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/faculdadedombosco/imagens/recurso.png"))); // NOI18N
        itemDeMenuRecurso.setText("Recurso");
        itemDeMenuRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuRecursoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemDeMenuRecurso);

        itemDeMenuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        itemDeMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/faculdadedombosco/imagens/usuario.png"))); // NOI18N
        itemDeMenuUsuario.setText("Usuário");
        itemDeMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuUsuarioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemDeMenuUsuario);

        menuBar.add(menuCadastro);

        menuRelatorio.setText("Relatório");

        itemDeMenuRelatorioDeAgendamento.setText("Agendamento");
        itemDeMenuRelatorioDeAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuRelatorioDeAgendamentoActionPerformed(evt);
            }
        });
        menuRelatorio.add(itemDeMenuRelatorioDeAgendamento);

        itemDeMenuRelatorioDeEquipamento.setText("Equipamento");
        itemDeMenuRelatorioDeEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuRelatorioDeEquipamentoActionPerformed(evt);
            }
        });
        menuRelatorio.add(itemDeMenuRelatorioDeEquipamento);

        itemDeMenuRelatorioDeGradeDisciplina.setText("Grade Disciplina");
        itemDeMenuRelatorioDeGradeDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuRelatorioDeGradeDisciplinaActionPerformed(evt);
            }
        });
        menuRelatorio.add(itemDeMenuRelatorioDeGradeDisciplina);

        itemDeMenuRelatorioDeRecurso.setText("Recurso");
        itemDeMenuRelatorioDeRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuRelatorioDeRecursoActionPerformed(evt);
            }
        });
        menuRelatorio.add(itemDeMenuRelatorioDeRecurso);

        itemDeMenuRelatorioDeUsuario.setText("Usuário");
        itemDeMenuRelatorioDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuRelatorioDeUsuarioActionPerformed(evt);
            }
        });
        menuRelatorio.add(itemDeMenuRelatorioDeUsuario);

        menuBar.add(menuRelatorio);

        menuAjuda.setText("Ajuda");

        itemDeMenuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        itemDeMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic/faculdadedombosco/imagens/ajuda.png"))); // NOI18N
        itemDeMenuSobre.setText("Sobre");
        itemDeMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(itemDeMenuSobre);

        menuBar.add(menuAjuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1246, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemDeMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuSairActionPerformed
        //pers.FecharConexao();
        System.exit(0);
    }//GEN-LAST:event_itemDeMenuSairActionPerformed

    private void itemDeMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuUsuarioActionPerformed
        if((guicadusu == null) || (!guicadusu.isVisible())){
            guicadusu = new GUIUsuario();
            desktopPane.add(guicadusu);
            guicadusu.setPosicao();
            guicadusu.setVisible(true);
        }
    }//GEN-LAST:event_itemDeMenuUsuarioActionPerformed

    private void itemDeMenuRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuRecursoActionPerformed
       if((guicadrec == null) || (!guicadrec.isVisible())){
            guicadrec = new GUIRecurso();
            desktopPane.add(guicadrec);
            guicadrec.setPosicao();
            guicadrec.setVisible(true);
        }
    }//GEN-LAST:event_itemDeMenuRecursoActionPerformed

    private void itemDeMenuGradeDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuGradeDisciplinaActionPerformed
        if((guigradedisciplina == null) || (!guigradedisciplina.isVisible())){
            guigradedisciplina = new GUIGradeDisciplina();
            desktopPane.add(guigradedisciplina);
            guigradedisciplina.setPosicao();
            guigradedisciplina.setVisible(true);
        }
    }//GEN-LAST:event_itemDeMenuGradeDisciplinaActionPerformed

    private void itemDeMenuAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuAgendamentoActionPerformed
        if((guimovagend == null) || (!guimovagend.isVisible())){
            guimovagend = new GUIMovimentacaoAgendamento();
            desktopPane.add(guimovagend);
            guimovagend.setPosicao();
            guimovagend.setVisible(true);
        }
    }//GEN-LAST:event_itemDeMenuAgendamentoActionPerformed

    private void itemDeMenuRelatorioDeEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuRelatorioDeEquipamentoActionPerformed
        JOptionPane.showMessageDialog(null, "Módulo em construção...", "Atenção!!!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemDeMenuRelatorioDeEquipamentoActionPerformed

    private void itemDeMenuRelatorioDeGradeDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuRelatorioDeGradeDisciplinaActionPerformed
        JOptionPane.showMessageDialog(null, "Módulo em construção...", "Atenção!!!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemDeMenuRelatorioDeGradeDisciplinaActionPerformed

    private void itemDeMenuRelatorioDeRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuRelatorioDeRecursoActionPerformed
        JOptionPane.showMessageDialog(null, "Módulo em construção...", "Atenção!!!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemDeMenuRelatorioDeRecursoActionPerformed

    private void itemDeMenuRelatorioDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuRelatorioDeUsuarioActionPerformed
        JOptionPane.showMessageDialog(null, "Módulo em construção...", "Atenção!!!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemDeMenuRelatorioDeUsuarioActionPerformed

    private void itemImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemImprimirActionPerformed
        JOptionPane.showMessageDialog(null, "Módulo em construção...", "Atenção!!!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemImprimirActionPerformed

    private void itemDeMenuEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuEquipamentoActionPerformed
        if((guicadequip == null) || (!guicadequip.isVisible())){
            guicadequip = new GUIEquipamento();
            desktopPane.add(guicadequip);
            guicadequip.setPosicao();
            guicadequip.setVisible(true);
        }
}//GEN-LAST:event_itemDeMenuEquipamentoActionPerformed

    private void itemDeMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuSobreActionPerformed
        if((guisobre == null) || (!guisobre.isVisible())){
            guisobre = new GUISobre();
            desktopPane.add(guisobre);
            guisobre.setPosicao();
            guisobre.setVisible(true);
        }

        //SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy - hh-mm-ss");
        //Date  hora = new Date();
        //String horaatual = formatador.format(hora);
        //ldiasemana_hora.setText(horaatual);
}//GEN-LAST:event_itemDeMenuSobreActionPerformed

    private void itemDeMenuRelatorioDeAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuRelatorioDeAgendamentoActionPerformed
        if((guirelatagend == null) || (!guirelatagend.isVisible())){
            guirelatagend = new GUIRelatorioAgendamento();
            desktopPane.add(guirelatagend);
            guirelatagend.setPosicao();
            guirelatagend.setVisible(true);
        }
    }//GEN-LAST:event_itemDeMenuRelatorioDeAgendamentoActionPerformed

    public void Calendario(){
        if((guicalendar == null) || (!guicalendar.isVisible())){
            guicalendar = new GUICalendario();
            desktopPane.add(guicalendar);
            guicalendar.setPosicao();
            guicalendar.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemDeMenuAgendamento;
    private javax.swing.JMenuItem itemDeMenuEquipamento;
    private javax.swing.JMenuItem itemDeMenuGradeDisciplina;
    private javax.swing.JMenuItem itemDeMenuRecurso;
    private javax.swing.JMenuItem itemDeMenuRelatorioDeAgendamento;
    private javax.swing.JMenuItem itemDeMenuRelatorioDeEquipamento;
    private javax.swing.JMenuItem itemDeMenuRelatorioDeGradeDisciplina;
    private javax.swing.JMenuItem itemDeMenuRelatorioDeRecurso;
    private javax.swing.JMenuItem itemDeMenuRelatorioDeUsuario;
    private javax.swing.JMenuItem itemDeMenuSair;
    private javax.swing.JMenuItem itemDeMenuSobre;
    private javax.swing.JMenuItem itemDeMenuUsuario;
    private javax.swing.JMenuItem itemImprimir;
    private javax.swing.JPopupMenu.Separator itemSeparador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuRelatorio;
    // End of variables declaration//GEN-END:variables

    private GUIEquipamento guicadequip;
    private GUIMovimentacaoAgendamento guimovagend;
    private GUIRecurso guicadrec;
    private GUIUsuario guicadusu;
    private GUIVinUsuRec guivinusurec;
    private GUISobre guisobre;
    private GUICalendario guicalendar;
    private GUIRelatorioAgendamento guirelatagend;
    private GUIGradeDisciplina guigradedisciplina;
}
